TARGET = HW6
SRC_FILES = main.cpp meshType.cpp volScalarField.cpp surfaceScalarField.cpp velocityField.cpp FileIO.cpp bcType.cpp Time.cpp linSysType.cpp fieldVal.cpp

CXXFLAGS += -I../eigen
# NO EDITS NEEDED BELOW THIS LINE

CXX = g++
CXXFLAGS = -Wall -Wextra -Werror -pedantic-errors
CXXFLAGS_DEBUG = -g
CXXVERSION = -std=c++17

OBJECTS = $(SRC_FILES:.cpp=.o)

ifeq ($(shell echo "Windows"), "Windows")
	TARGET := $(TARGET).exe
	DEL = del
	Q =
else
	DEL = rm -f
	Q = "
endif

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CXX) -o $@ $^

.cpp.o:
	$(CXX) $(CXXFLAGS) $(CXXVERSION) $(CXXFLAGS_DEBUG) -o $@ -c $<

clean:
	$(DEL) $(TARGET) $(OBJECTS)

depend:
	@sed -i.bak '/^# DEPENDENCIES/,$$d' Makefile
	@$(DEL) sed*
	@echo $(Q)# DEPENDENCIES$(Q) >> Makefile
	@$(CXX) -MM $(SRC_FILES) >> Makefile

.PHONY: all clean depend

# DEPENDENCIES 
meshType.o: meshType.cpp meshType.h FileIO.h
volScalarField.o: volScalarField.cpp meshType.h FileIO.h volScalarField.h \
 bcType.h FileIO.H fieldVal.h Time.h
surfaceScalarField.o: surfaceScalarField.cpp surfaceScalarField.h \
 meshType.h FileIO.h volScalarField.h bcType.h FileIO.H fieldVal.h \
 velocityField.h Time.h
velocityField.o: velocityField.cpp velocityField.h meshType.h FileIO.h \
 Time.h
FileIO.o: FileIO.cpp FileIO.h
bcType.o: bcType.cpp bcType.h FileIO.H
Time.o: Time.cpp Time.h FileIO.h
fieldVal.o: fieldVal.cpp fieldVal.h
